SELECT
    YEAR(o.SALES_DATE) AS YEAR,
    MONTH(o.SALES_DATE) AS MONTH,
    u.GENDER AS GENDER,
    COUNT(DISTINCT u.USER_ID) AS USERS
FROM 
    USER_INFO u
INNER JOIN
    ONLINE_SALE o
ON 
    u.USER_ID = o.USER_ID
GROUP BY
    YEAR, MONTH, GENDER
HAVING
    GENDER IS NOT NULL
ORDER BY
    YEAR, MONTH, GENDER