SELECT DATE_FORMAT(o.SALES_DATE, '%Y') AS YEAR,
        DATE_FORMAT(o.SALES_DATE, '%m') AS MONTH,
        COUNT(DISTINCT u.USER_ID) AS PURCHASED_USERS,
        ROUND(COUNT(DISTINCT u.USER_ID)/(SELECT COUNT(*) FROM USER_INFO u WHERE YEAR(u.JOINED)=2021), 1) AS PURCHASED_RATIO
FROM USER_INFO u
INNER JOIN ONLINE_SALE o ON u.USER_ID = o.USER_ID
WHERE YEAR(u.JOINED)=2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH