-- 코드를 입력하세요
SELECT
    u.USER_ID AS USER_ID, 
    u.NICKNAME AS NICKNAME, 
    SUM(b.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD b
INNER JOIN USED_GOODS_USER u 
    ON b.WRITER_ID = u.USER_ID
WHERE b.STATUS = "DONE"
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES