WITH MAX_SIZE_OF_COLONY_PER_YEAR AS(
    SELECT 
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
    FROM
        ECOLI_DATA
    GROUP BY YEAR
),
ECOLI_YEAR_DATA AS(
    SELECT 
        e.ID,
        EXTRACT(YEAR FROM e.DIFFERENTIATION_DATE) AS YEAR,
        MAX_SIZE_OF_COLONY - e.SIZE_OF_COLONY AS YEAR_DEV
    FROM 
        ECOLI_DATA e
    INNER JOIN
        MAX_SIZE_OF_COLONY_PER_YEAR m
    ON
        EXTRACT(YEAR FROM e.DIFFERENTIATION_DATE)=m.YEAR
)

SELECT YEAR, YEAR_DEV, ID
FROM ECOLI_YEAR_DATA
ORDER BY YEAR, YEAR_DEV;