SELECT 
    b.CATEGORY,
    SUM(s.SALES) AS TOTAL_SALES
FROM 
    BOOK b
INNER JOIN
    BOOK_SALES s
ON 
    b.BOOK_ID = s.BOOK_ID
WHERE
    Year(s.SALES_DATE) = 2022 
    AND Month(s.SALES_DATE) = 1
GROUP BY
    b.CATEGORY
ORDER BY 
    b.CATEGORY